---
- name: "Fail if OS/Architecture is not supported"
  fail:
    msg: "Installing ospf on {{ (ansible_os_family | lower) + '_' + (ansible_architecture | lower) }} is unsupported."
  when:
    - "(install_ospf_packages | default({}))[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] is not defined"
    - "ospf is defined"
  tags:
    - "ospf"
- name: "Install ospf"
  package:
    pkg: "{{ install_ospf_packages[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
    state: "present"
  when:
    - "ospf is defined"
  tags:
    - "ospf"
